### PR TITLE
[v2] lean on the type system better around error parsing

### LINKED ISSUE #155: Repo cloning error dialogue
Perhaps we can change the error dialogue to something more understandable to the layman? and do we need some validation on the url field? I entered some jiberish in the url field and got this:

33733870-ff4b191a-db3f-11e7-92f5-92d63e12b50f
33733867-ff1ce9dc-db3f-11e7-948a-9baa8f16140e

1.0.11-beta0, mac

related to: https://github.com/desktop/desktop/issues/3539

### LINKED ISSUE #156: Clean up the error message
When reverting a commit I got an error message that looks to include double "hints" even though it appears to be one sentence.

I believe it should read:

`error: Reverting is not possible because you have unmerged files.`
`hint: Fix them up in the work tree, and then use 'git add/rm <file>',`
`as appropriate, to mark resolution and make a commit.`
`fatal: revert failed`

Current error:
screen shot 2017-12-12 at 9 14 29 am

1.0.11-beta0, mac

Ref:
https://github.com/desktop/desktop/issues/3579

---

It looks like this is coming from git itself:

https://github.com/git/git/blob/7668cbc60578f99a4c048f8f8f38787930b8147b/advice.c#L106-L107

https://github.com/git/git/blob/7668cbc60578f99a4c048f8f8f38787930b8147b/advice.c#L48-L65

So to customize this we'd need to parse this error in dugite.

### PR DESCRIPTION
**Pull request by shiftkey**
This PR makes the original `GitError` enum (which is backed by numbers) into a string enum that uses a human-friendly string as the backing store.

This is annoying for scenarios where you're testing the error code raised:

```shellsession
 FAIL  test/fast/git-process-test.ts
  ● git-process › errors › can parse the no merge to abort error

    expect(received).toBe(expected) // Object.is equality

    Expected: 8
    Received: 35

      391 |
      392 |       const error = GitProcess.parseError(stderr)
    > 393 |       expect(error).toBe(GitError.HTTPSRepositoryNotFound)
          |                     ^
      394 |     })
      395 |   })
      396 | })

      at Object.it (test/fast/git-process-test.ts:393:21)
```

What's the actual value I receive here? You need to literally count the number of entries in `GitError` to get to the 35th one:

With this change, it becomes infinitely easier to understand:

```shellsession
 FAIL  test/fast/git-process-test.ts
  ● git-process › errors › can parse the no merge to abort error

    expect(received).toBe(expected) // Object.is equality

    Expected: "https-repository-not-found"
    Received: "no-merge-to-abort"

      390 |
      391 |       const error = GitProcess.parseError(stderr)
    > 392 |       expect(error).toBe(GitError.HTTPSRepositoryNotFound)
          |                     ^
      393 |     })
      394 |   })
      395 | })

      at Object.it (test/fast/git-process-test.ts:392:21)
```

Unfortunately this is a breaking change to the public API (`GitProcess.parseError` returns `GitError | null`), so I'll plan to bump `dugite` to a v2 once this change is merged. I also plan to write a migration guide using GitHub Desktop as an example (it uses this error parsing heavily) as part of this process.

Meanwhile I'm also going to fix a couple of related error parsing bugs:

 - Fixes #156
 - Fixes #155 

TODO:

 - [x] update API to return string enum
 - [x] write migration guide

### CODE REVIEW

File: lib/errors.ts [hunk 1]
```diff
@@ -1,121 +1,199 @@
...
-  "fatal: .+: '(.+)' is outside repository": GitError.OutsideRepository,
-  'Another git process seems to be running in this repository, e.g.':
-    GitError.LockFileAlreadyExists,
-  'fatal: There is no merge to abort': GitError.NoMergeToAbort,
+
+export const GitErrorRegexes = new Map<RegExp, GitError>([
+  [
+    new RegExp(
+      'ERROR: ([\\s\\S]+?)\\n+\\[EPOLICYKEYAGE\\]\\n+fatal: Could not read from remote repository.'
+    ),
```
Comment (j-f1) [inline lib/errors.ts]: Why not use `/.../` regexes here?

Comment (shiftkey) [reply lib/errors.ts]: Mostly because I was afraid of breaking them while reorganizing the source 🤷‍♂️

Comment (shiftkey) [reply lib/errors.ts]: Yep, I tried and changed these around in syntax and broke some tests - probably because of things like escaping special characters.

Gonna leave them alone for now.

Comment (j-f1) [reply lib/errors.ts]: <details><summary>These should work:</summary>

```ts
[/ERROR: ([\s\S]+?)\n+\[EPOLICYKEYAGE\]\n+fatal: Could not read from remote repository./, GitError.SSHKeyAuditUnverified],
[/fatal: Authentication failed for 'https:\/\//, GitError.HTTPSAuthenticationFailed],
[/fatal: Authentication failed/, GitError.SSHAuthenticationFailed],
[/fatal: Could not read from remote repository./, GitError.SSHPermissionDenied],
[/The requested URL returned error: 403/, GitError.HTTPSAuthenticationFailed],
[/fatal: The remote end hung up unexpectedly/, GitError.RemoteDisconnection],
[/fatal: unable to access '(.+)': Failed to connect to (.+): Host is down/, GitError.HostDown],
[/Failed to merge in the changes./, GitError.RebaseConflicts],
[/(Merge conflict|Automatic merge failed; fix conflicts and then commit the result)/, GitError.MergeConflicts],
[/fatal: repository '(.+)' not found/, GitError.HTTPSRepositoryNotFound],
[/ERROR: Repository not found/, GitError.SSHRepositoryNotFound],
[/\((non-fast-forward|fetch first)\)\nerror: failed to push some refs to '.*'/, GitError.PushNotFastForward],
[/error: unable to delete '(.+)': remote ref does not exist/, GitError.BranchDeletionFailed],
[/\[remote rejected\] (.+) \(deletion of the current branch prohibited\)/, GitError.DefaultBranchDeletionFailed],
[/error: could not revert .*\nhint: after resolving the conflicts, mark the corrected paths\nhint: with 'git add <paths>' or 'git rm <paths>'\nhint: and commit the result with 'git commit'/, GitError.RevertConflicts],
[/Applying: .*\nNo changes - did you forget to use 'git add'\?\nIf there is nothing left to stage, chances are that something else\n.*/, GitError.EmptyRebasePatch],
[/There are no candidates for (rebasing|merging) among the refs that you just fetched.\nGenerally this means that you provided a wildcard refspec which had no\nmatches on the remote end./, GitError.NoMatchingRemoteBranch],
[/nothing to commit/, GitError.NothingToCommit],
[/No submodule mapping found in .gitmodules for path '(.+)'/, GitError.NoSubmoduleMapping],
[/fatal: repository '(.+)' does not exist\nfatal: clone of '.+' into submodule path '(.+)' failed/, GitError.SubmoduleRepositoryDoesNotExist],
[/Fetched in submodule path '(.+)', but it did not contain (.+). Direct fetching of that commit failed./, GitError.InvalidSubmoduleSHA],
[/fatal: could not create work tree dir '(.+)'.*: Permission denied/, GitError.LocalPermissionDenied],
[/merge: (.+) - not something we can merge/, GitError.InvalidMerge],
[/invalid upstream (.+)/, GitError.InvalidRebase],
[/fatal: Non-fast-forward commit does not make sense into an empty head/, GitError.NonFastForwardMergeIntoEmptyHead],
[/error: (.+): (patch does not apply|already exists in working directory)/, GitError.PatchDoesNotApply],
[/fatal: A branch named '(.+)' already exists./, GitError.BranchAlreadyExists],
[/fatal: bad revision '(.*)'/, GitError.BadRevision],
[/fatal: [Nn]ot a git repository \(or any of the parent directories\): (.*)/, GitError.NotAGitRepository],
[/fatal: refusing to merge unrelated histories/, GitError.CannotMergeUnrelatedHistories],
[/The .+ attribute should be .+ but is .+/, GitError.LFSAttributeDoesNotMatch],
[/fatal: Branch rename failed/, GitError.BranchRenameFailed],
[/fatal: Path '(.+)' does not exist .+/, GitError.PathDoesNotExist],
[/fatal: Invalid object name '(.+)'./, GitError.InvalidObjectName],
[/fatal: .+: '(.+)' is outside repository/, GitError.OutsideRepository],
[/Another git process seems to be running in this repository, e.g./, GitError.LockFileAlreadyExists],
[/fatal: There is no merge to abort/, GitError.NoMergeToAbort],
[/error: GH001: /, GitError.PushWithFileSizeExceedingLimit],
[/error: GH002: /, GitError.HexBranchNameRejected],
[/error: GH003: Sorry, force-pushing to (.+) is not allowed./, GitError.ForcePushRejected],
[/error: GH005: Sorry, refs longer than (.+) bytes are not allowed/, GitError.InvalidRefLength],
[/error: GH006: Protected branch update failed for (.+)\nremote: error: At least one approved review is required/, GitError.ProtectedBranchRequiresReview],
[/error: GH006: Protected branch update failed for (.+)\nremote: error: Cannot force-push to a protected branch/, GitError.ProtectedBranchForcePush],
[/error: GH006: Protected branch update failed for (.+)\nremote: error: Cannot delete a protected branch/, GitError.ProtectedBranchDeleteRejected],
[/error: GH006: Protected branch update failed for (.+).\nremote: error: Required status check "(.+)" is expected/, GitError.ProtectedBranchRequiredStatus],
[/error: GH007: Your push would publish a private email address./, GitError.PushWithPrivateEmail],
```

(brought  to you by [this code](https://stackblitz.com/edit/typescript-ekfttq))

Comment (shiftkey) [reply lib/errors.ts]: 49303de06fb129786121b6d4918f864601e3e0f8
