### PR TITLE
GH-129: Skip external tests gracefully when executable is not found.

### LINKED ISSUE #129: External tests fail instead of being gracefully skipped when executable does not exist on the host
That is something I have accidentally overlooked [here](https://github.com/desktop/dugite/blob/fcfe8fa5b465417b70bf7861a8a6ae1bce1b2067/test/external/git-process-external-test.ts#L15).

The `findGit` call should be wrapped in a `try-catch` block.

I will take care of this.

### PR DESCRIPTION
**Pull request by kittaakos**
Previously, tests failed with an error.

Closes #129.

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

File: test/external/git-process-external-test.ts [hunk 1]
```diff
@@ -12,7 +12,11 @@ describe('git-process [with external Git executable]', () => {
   let git: Git | undefined
 
   before(async () => {
-    git = await findGit()
+    try {
+      git = await findGit()
+    } catch (error) {
+      git = undefined
```
Comment (shiftkey) [inline test/external/git-process-external-test.ts]: You could move this up to line 12 and have `let git: Git | undefined = undefined`

Comment (shiftkey) [reply test/external/git-process-external-test.ts]: And the `catch` here can be defined without `error` in TS 2.5 - see https://github.com/desktop/dugite/pull/132 for more info

**Comment by shiftkey** [comment]
@kittaakos thanks!
